### ISSUE TITLE
I run `boot dev` but it shows error `The following artifacts could not be resolved: `

### ISSUE THREAD

**Issue by cmal** [upgradingdave/cljs#2]
> 
>  clojure.lang.ExceptionInfo: The following artifacts could not be resolved: upgradingdave:boot-dave:jar:0.1.1, upgradingdave:password:jar:0.2.2: Could not find artifact upgradingdave:boot-dave:jar:0.1.1 in clojars (https://clojars.org/repo/)
>     data: {:file
>            "/var/folders/3n/cbv5r8rd2bj_f6lpjr2ck0_r0000gn/T/boot.user3862548369574636982.clj",
>            :line 5}
> org.sonatype.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: upgradingdave:boot-dave:jar:0.1.1, upgradingdave:password:jar:0.2.2: Could not find artifact upgradingdave:boot-dave:jar:0.1.1 in clojars (https://clojars.org/repo/)
>     result: ...

How could I find these artifacts? Thanks!

**Comment by upgradingdave** [comment]
Hi @cmal, I submitted boot-dave to clojars, removed unused password dep, and checked in my latest code.

If you pull the latest, I think it should work for you now. Note that the README incorrectly said to browse to dev.html, but I corrected it to say to browse to http://localhost:3000/index.html

If all works correctly, you should see a bunch of devcards at index.html. There's some css examples at http://localhost:3000/index.html#!/up.css.dev

Feel free to ping me on clojurians slack if you have any questions.

Sorry in advance for the messiness of some of the code. This is a playground where I experiment with new ideas with cljs. 

Hope it's helpful. 

Dave

**Comment by cmal** [comment]
Thank you very much. I can learn a lot from this repo.
